"""Scheduler state access: models, stores, versioned document schema,
the durable backend-authority protocol, and the routing seam that selects
a backend from that authority."""
from __future__ import annotations

from .models import ProviderState, ResetCandidate
from .schema import (
    SCHEMA_VERSION,
    DocumentCorruptError,
    MissingStateDocumentError,
    SchemaError,
    deserialize_state,
    document_to_state,
    parse_document_bytes,
    serialize_state,
    validate_document,
    validate_state,
)
from .store import (
    FileStateStore,
    ProviderStateStore,
    StaleStateError,
    StateStoreError,
)
from .json_store import JsonStateStore, document_filename
from .authority import (
    AUTHORITY_FILENAME,
    AUTHORITY_SCHEMA_VERSION,
    BACKEND_JSON,
    BACKEND_LEGACY,
    SUPPORTED_BACKENDS,
    AuthorityCorruptError,
    AuthorityError,
    AuthoritySchemaError,
    BackendAuthority,
    ConcurrentAuthorityChangeError,
    authority_path,
    bootstrap_authority,
    parse_authority,
    read_authority,
    read_authority_if_present,
    serialize_authority,
    write_authority,
)
from .router import AuthoritativeStateStore
from .cutover import (
    CutoverPreparation,
    CutoverVerificationError,
    RollbackRefusedError,
    BackendSwitch,
    cutover_to_json,
    prepare_all_cutover,
    prepare_provider_cutover,
    rollback_to_legacy,
)
from .migration import (
    ACTION_EXISTS,
    ACTION_SEEDED,
    DEFAULT_PROVIDERS,
    migrate_all,
    migrate_provider,
    seed_document_if_absent,
)

__all__ = [
    "ProviderState",
    "ResetCandidate",
    "ProviderStateStore",
    "FileStateStore",
    "JsonStateStore",
    "document_filename",
    "StateStoreError",
    "StaleStateError",
    "SCHEMA_VERSION",
    "SchemaError",
    "DocumentCorruptError",
    "MissingStateDocumentError",
    "document_to_state",
    "validate_document",
    "validate_state",
    "serialize_state",
    "parse_document_bytes",
    "deserialize_state",
    "DEFAULT_PROVIDERS",
    "migrate_provider",
    "migrate_all",
    "seed_document_if_absent",
    "ACTION_SEEDED",
    "ACTION_EXISTS",
    "CutoverPreparation",
    "prepare_provider_cutover",
    "prepare_all_cutover",
    "AUTHORITY_FILENAME",
    "AUTHORITY_SCHEMA_VERSION",
    "BACKEND_JSON",
    "BACKEND_LEGACY",
    "SUPPORTED_BACKENDS",
    "AuthorityError",
    "AuthorityCorruptError",
    "AuthoritySchemaError",
    "ConcurrentAuthorityChangeError",
    "BackendAuthority",
    "authority_path",
    "bootstrap_authority",
    "parse_authority",
    "read_authority",
    "read_authority_if_present",
    "serialize_authority",
    "write_authority",
    "AuthoritativeStateStore",
    "BackendSwitch",
    "CutoverVerificationError",
    "RollbackRefusedError",
    "cutover_to_json",
    "rollback_to_legacy",
]
